config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
    member do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
  end
  resources "items", only: [:show] do
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :purchase_informations
  has_many :items
  has_one :credit_card, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases
  has_one :card, dependent: :destroy

         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
         validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX, message: "＠とドメインを含む必要があります"}
         validates :nickname, presence: true, uniqueness: true
         validates :password, presence: true, length: { minimum: 7 }
         validates :family_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/, message: "全角のみで入力して下さい"}
         validates :first_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/, message: "全角のみで入力して下さい"}
         validates :family_name_furigana, presence: true, format: {with: /\A[ぁ-んァ-ヶー－]+\z/, message: "全角ひらがな、全角カタカナのみで入力して下さい"}
         validates :first_name_furigana, presence: true, format: {with: /\A[ぁ-んァ-ヶー－]+\z/, message: "全角ひらがな、全角カタカナのみで入力して下さい"}
         validates :birth_day, presence: true
         validates :family_name_to_deliver, presence: true
         validates :first_name_to_deliver, presence: true
         validates :family_name_to_deliver_furigana, presence: true
         validates :first_name_to_deliver_furigana, presence: true
         validates :post_code, presence: true
         validates :prefecture_id, presence: true
         validates :city_name, presence: true
         validates :city_address, presence: true
         
         extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to_active_hash :prefecture
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
  end
  
end

app/views/users/_user_side.html.haml
.user__side
  .user__side__menu
    = link_to "トップページ", root_path, class: "link"
  .user__side__menu
    = link_to "マイページ", root_path, class: "link"
  .user__side__menu
    = link_to "お気に入り商品一覧", root_path, class: "link"
  .user__side__menu
    = link_to "出品する", new_item_path, data: {"turbolinks" => false} , class: "link"
  .user__side__menu
    = link_to "出品中の商品一覧", root_path, class: "link"
  .user__side__menu
    = link_to "売却済の商品一覧", root_path, class: "link"
  .user__side__menu
    = link_to "コメントがついた商品一覧", root_path, class: "link"
  .user__side__subtitle 各種設定
  .user__side__menu
    = link_to "会員情報の編集", root_path, class: "link"
  .user__side__menu
    = link_to "お届先住所の編集", root_path, class: "link"
  .user__side__menu
    = link_to "お支払い情報の登録/確認/削除", new_card_path, data: {"turbolinks" => false}, class: "link"
  .user__side__menu
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" 

app/views/users/show.html.haml
.Header
  = render "layouts/header"
.UserMain
  .main
    .user
      = render 'user_side'
    .user__body
      .user__body__bgc
        .userlisence
          .userlisence--title
            Trading License
          .userlisence--name
            %p
              = @nickname
              様
        .prof
          .prof__data
            登録日：aaa
          .prof__data
            現在の出品数：aaa
          .prof__data
            コメントされた数：aaa
          .prof__data
            コメントした数：aaa
      .user__body__subtitle
        最近出品した商品
      .user__body__lists
.Aside
  = render "layouts/aside"
.Footer
  = render "layouts/footer"

      