config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
    member do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
  end
  resources "items", only: [:show] do
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  resources :users, only: :show
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require "payjp"

  def buy
    @item = Item.find(params[:item_id])

    if user_signed_in?
      @user = current_user
      if @user.card.present?
        Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
        @card = Card.find_by(user_id: current_user.id)
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @customer_card = customer.cards.retrieve(@card.card_id)

        @exp_month = @customer_card.exp_month.to_s
        @exp_year = @customer_card.exp_year.to_s.slice(2,3)
      else
        redirect_to new_card_path, alert: "クレジットカードを登録してください"
      end
    else
      redirect_to user_session_path, alert: "ログインしてください"
    end
  end
  
  def pay
    @item = Item.find(params[:item_id])

    if @item.purchases.present?
      redirect_to item_path(@item.id), alert: "売り切れています。"
    else
      @item.with_lock do
        if current_user.card.present?
          @card = Card.find_by(user_id: current_user.id)
          Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
          charge = Payjp::Charge.create(
          amount: @item.price,
          customer: Payjp::Customer.retrieve(@card.customer_id),
          currency: 'jpy'
          )
          redirect_to root_path, notice: "購入しました。"
        else
          Payjp::Charge.create(
          amount: @item.price,
          card: params['payjp-token'],
          currency: 'jpy'
          )
        end
      @purchase = Purchase.create(user_id: current_user.id, item_id: params[:item_id])
      end
    end
  end
end

app/views/purchases/buy.html.haml
%main.PurchaseMain
  .Header
    .Logo
      =  link_to image_tag("material/logo/logo.png", class: "Logo__image"),root_path
  .Content
    %h2.Title 購入内容の確認
    .Item
      .Item__image
        = image_tag("#{@item.item_images[0].url}", class: "Item__image__img")
      .Item__box
        .Item__box__name
          = "#{@item.name}"
        .Item__box__price
          .Item__box__price__sipping
            送料込み（税込み）
          .Item__box__price__amount
            = "¥" + "#{@item.price}"
    .Wrapper
      .Content__price
        .Content__price__text
          支払い金額
        .Content__price__amount
          = "¥" + "#{@item.price}"
      .Content__point
        .Content__point__text
          ポイント
        .Content__point__amount
          所持ポイント：P0

      - if @user.card.present?
        .Content__payment
          %p.Content__payment__text
            支払い方法
          %p.Content__payment__method
            クレジットカード
          %p.Content__payment__number
            = "**** **** **** " + @customer_card.last4
          %p.Content__payment__expiration
            = "有効期限" + @exp_month + " / " + @exp_year

        .Content__userAdoress
          %h2.Content__userAdoress__text
            配送先
          %p.Content__userAdoress__postalCode
            = "〒" + "#{@user.post_code}"
          %p.Content__userAdoress__streetAddress
            = "#{@user.city_name}" + "#{@user.city_address}"
          %p.Content__userAdoress__name
            = "#{@user.family_name}" + "#{@user.first_name}"
        .Content__buy
          = link_to "購入する", pay_item_purchases_path(item_id: @item.id), method: :post, class: "Content__buy__btn"
  .PurchaseFooter
    .Terms
      %ul.Terms__contents
        %li.Terms__contents__content
          %a(href="#") プライバシーポリシー
        %li.Terms__contents__content
          %a(href="#") フリマ利用規約
        %li.Terms__contents__content
          %a(href="#") 特定商取引に関する表記
    .Logo
      .Title
        = link_to image_tag("material/logo/logo.png", class: "Title__image"),root_path

      .Text
        ©︎ FURIMA