config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
    member do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
  end
  resources "items", only: [:show] do
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  resources :users, only: :show
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true, reject_if: :no_image, update_only: true
  has_many :purchase_informations
  has_many :comments
  belongs_to :user
  belongs_to :category
  has_many :purchases
  # belongs_to :brand
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :state
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :prefecture

  # validates_associated :item_images
  validates :name, presence: true, length: { maximum: 40 }
  validates :explanation, presence: true, length: { maximum: 1000 }
  validates :size_id, presence: true
  validates :state_id, presence: true
  validates :shipping_charge_id, presence: true
  validates :shipping_date_id, presence: true
  validates :prefecture_id, presence: true
  validates :price, presence: true
  validates :item_images, length: { minimum: 1, maximum: 5, message: "の数が不正です" } 

  def no_image(item_images_attributes)
    item_images_attributes[:url].blank?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :category_parent_array, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:show, :destroy, :edit, :update]
  before_action :baria_user, only: [:edit, :update]
  before_action :category, only: [:edit, :update]

  def index
    @items = Item.all.order('created_at DESC')
    @purchases = Purchase.all
  end


  def show
    @item_images = @item.item_images
    @category_id = @item.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
  end

  def new
    @item = Item.new
    @item.item_images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path(@item.user_id), notice: '出品が完了しました'
    else
      flash.now[:alert] = 'エラー : 必須項目を入力してください。'
      render :new
    end
  end

  def purchase
  end

  def edit
    @item.item_images.new
  end

  def update
    if @item.update(item_params)
      redirect_to root_path, notice: '出品内容を更新しました'
    else
      flash.now[:alert] = 'エラー : 必須項目を入力してください。'
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: '削除しました'
    else
      flash.now[:alert] = 'エラー : 削除できませんでした。'
      render :show
    end
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def category
    @category_grandchild = @item.category
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    @category = Category.find(params[:id])
    @category_children = @item.category.parent.parent.children
    @category_grandchildren = @item.category.parent.children
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :price, :explanation, :category_id, :brand, :size_id, :state_id, :shipping_charge_id, :prefecture_id, :shipping_date_id, item_images_attributes: [:url, :id, :_destroy]).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil)
  end
  
  def baria_user
    redirect_to root_path, alert: '出品者以外は編集・削除が出来ません' unless @item.user == current_user
  end

  def set_item
    @item = Item.find(params[:id])
    @item_images = @item.item_images
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.sell__header
  .sell__header__logo
    = link_to "/" do
      = image_tag("material/logo/logo.png",class: 'sell__header__logo')
=form_with model: [@item], local: true do |f|
  .sell-container
    .sell-container__white
      .sell-box
        .sell-title
          .sell-title__group
            %label.sell__text
              出品画像
            %span.sell__require
              必須
          %p.sell-title__update
            最大5枚までアップロードできます
          #sell-image
            #previews
              - @item_images.each_with_index do |img, i|
              
                -if img.persisted?
                  #parent{data: {index: i}}
                    = image_tag img.url.url, class:"js-img", id: "js-img_#{i}"
                    .js-remove{"data-index": "#{i}", id: "remove_#{i}"} 削除
            - if @item.item_images.length >= 5
              .sell-image__box#image-box__container{style: "display: none"}
                =f.fields_for :item_images do |i|
                  .sell-image__box__input{"data-index": "#{i.index}"}
                    = i.file_field :url, class:"js-file", id:"item_item_images_attributes_#{i.index}_url"

                    = i.check_box :_destroy ,"data-index": "#{i.index}",class:"hidden-destroy"
                    %label{for: "img-file"}
                %i.fas.fa-camera
                %p.sell-image__box__text
                  クリックしてファイルをアップロード
            - else 
              .sell-image__box#image-box__container
                =f.fields_for :item_images do |i|
                  .sell-image__box__input{"data-index": "#{i.index}"}
                    = i.file_field :url, class:"js-file", id:"item_item_images_attributes_#{i.index}_url"
                    = i.check_box :_destroy ,"data-index": "#{i.index}",class:"hidden-destroy"
                    %label{for: "img-file"}
                %i.fas.fa-camera
                %p.sell-image__box__text
                  クリックしてファイルをアップロード
      .sell-box
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              商品名
            %span.sell__require
              必須
          =f.text_field :name, class: 'sell-title__text', placeholder: "40字まで"
        .sell-title
          .sell-title__group
            %label.sell__text
              商品の説明
            %span.sell__require
              必須  
          =f.text_area :explanation, class: 'sell-title__textbox', placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。\n          ",rows: "7"
          %p.word_count
            0/1000
      .sell-box
        .sell-box__header
          .sell__head
            %p 商品の詳細
        .sell-title__bottoms
          .sell-title__categoryWrapper
            %label.sell-title__categoryWrapper__text
              カテゴリー
            %span.sell-title__categoryWrapper__require
              必須
          .listing-select-wrapper
          = f.collection_select :category_id, @category_parent_array, :id, :name,{ selected: @category_parent.id}, class:"listing-select-wrapper--select"
          = f.collection_select :category_id, @category_children, :id, :name,{ selected: @category_child.id}, {class:"listing-select-wrapper--select", id: "child_category"}
          = f.collection_select :category_id, @category_grandchildren, :id, :name,{ selected: @category_grandchild.id}, {class:"listing-select-wrapper--select", id: "grandchild_category"}
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              サイズ
            %span.sell__require
              必須
          =f.collection_select :size_id, Size.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              ブランド
            %span.sell__require__gray
              任意
          -# %input{autocomplete: "off",name: "name", placeholder: "例） Apple", type: "text", value: "",class: "sell-title__text"}/
          =f.text_field :brand, class: 'sell-title__text', placeholder: "例） Apple"

        .sell-title
          .sell-title__group
            %label.sell__text
              商品の状態
            %span.sell__require
              必須
          =f.collection_select :state_id, State.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
      .sell-box
        .sell-box__header
          .sell__head
            %p 配送について
          = link_to "#" do
            %i.far.fa-question-circle
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              配送料の負担
            %span.sell__require
              必須
          =f.collection_select :shipping_charge_id, ShippingCharge.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              発送元の地域
            %span.sell__require
              必須
          =f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
        .sell-title
          .sell-title__group
            %label.sell__text
              発送までの日数
            %span.sell__require
              必須
          =f.collection_select :shipping_date_id, ShippingDate.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
      .sell-box
        .sell-box__header
          .sell__head
            %p 価格（¥300〜9,999,999）
          = link_to "#" do
            %i.far.fa-question-circle
        .sell-title
          .sell-title__price
            %label.sell__text
              販売価格
            %span.sell__require
              必須
            %span.sell__price
              ¥
            =f.number_field :price, min:300,max:999999999,placeholder: 0, id:"sell__box"
          .price__fee
            .price__commission
              %span.price__commission__left
                販売手数料（10%)
              %span.price__commission__right —
          .price__profit
            .price__commission
              .price__commission__left
                販売利益
              .profit__commission__right —
          .btn-group
            .submit-btn
              =f.submit "出品する",class: "submit-btn__mint",id: "mint_id",tabindex: 0
              =f.submit "下書きに保存",class: "submit-btn__gray",tabindex: 0
              -# %button.submit-btn__mint{tabindex: "0", type: "submit"} 出品する
              -# %button.submit-btn__gray{tabindex: "0", type: "submit"} 下書きに保存
            %li.link__back
              = link_to "もどる", "/"
          .sell-ban
            %p.sell-ban__text
              禁止されている
              %a.ban__text{href: "#"}> 行為
              および
              %a.ban__text{href: "#"}> 出品物
              を必ずご確認ください。
              %a.ban__text{href: "#"}> 偽ブランド品
              や
              %a.ban__text{href: "#"}> 盗品物
              などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
              %a.ban__text{href: "#"}> 加盟店規約
              に同意したことになります。
  .sell__footer
    %ul.sell__footer__link
      %li.link__text
        = link_to "プライバシーポリシー", "#"
      %li.link__text
        = link_to "フリマ利用規約", "#"
      %li.link__text
        = link_to "特定商取引に関する表記", "#"
    .sell__footer__logo
      = link_to "/" do
        = image_tag("material/logo/logo-white.png",class: 'sell__footer__logo')
    .sell__footer__inc
      © Furima, Inc.

app/views/items/index.html.haml
.Header
  = render "layouts/header"
%main.Main
  %section.Visual
    .Content
      %h2.Content__subtitle
        %br
        人生を変えるフリマアプリ
      %p.Content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .Content__icon
        %a.aBtn(href="#")
          = link_to image_tag("material/pict/app-store-.svg", class: "Content__icon--btn")
        %a.gBtn(href="#")
          = link_to image_tag("material/pict/google-play.svg",  class: "Content__icon--btn")

  %section.Introduction
    %h2.Title
      FURIMAが選ばれる3つの理由
    %ul.Lists
      %li.List
        .List__pict
          %span.List__pict--number 1
          = image_tag("material/pict/pict-reason-01.jpg", class:"List__pict--img")
        %h3.List__text
          %span 3分
          ですぐに出品
        %p.List__description
          スマホで入力するだけで簡単に出品できる！
      %li.List
        .List__pict
          %span.List__pict--number 2
          = image_tag("material/pict/pict-reason-02.jpg", class:"List__pict--img")
        %h3.List__text
          %span シンプル
          で使いやすい
        %p.List__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.List.list--last
        .List__pict
          %span.List__pict--number 3
          = image_tag("material/pict/pict-reason-03.jpg", class:"List__pict--img")
        %h3.List__text
          手数料
          %span 業界最安
        %p.List__description
          最大3%でお得に出品&amp;購入！
 
  %section.Number1Dl
    .Content
      %h2.Content__title 会員数日本一位
      %p.Content__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .Content__icon
        %a.aBtn(href="#")
          = link_to image_tag("material/pict/app-store-.svg", class: "Content__icon--btn")
        %a.gBtn(href="#")
          = link_to image_tag("material/pict/google-play.svg",  class: "Content__icon--btn")

  %section.Features
    %h2.Title FURIMAの特徴
    .Items
      .Item
        .Item__pict
          = image_tag("material/icon/icon-01.png", class:"Item__pict--img")
        %h3.Item__subtitle 簡単に売り買いできる
        %p.Item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .Item
        .Item__pict
          = image_tag("material/icon/icon-03.png", class:"Item__pict--img")
        %h3.Item__subtitle 売上金は即日振込みに対応
        %p.Item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .Item
        .Item__pict
          = image_tag("material/icon/icon-04.png", class:"Item__pict--img")
        %h3.Item__subtitle 様々な支払いに対応
        %p.Item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.PickupCategory
    %h2.Title ピックアップカテゴリー
    .ProductBox
      .ProductHead
        %a(href="#")
          %h3.ProductHead__title 新規投稿商品
      .ProductLists
        - @items.each do |item|
          .ProductList
            = link_to item_path(item.id), data: {"turbolinks" => false}  do
              %figure.ProductList__img
                = image_tag item.item_images[0].url.url
                - if item.purchases.present?
                  .ProductList__img__photo__sold
                    .ProductList__img__photo__sold__inner
                      SOLD
                - else
              .ProductList__body
                %h3.ProductList__body--ProductList__body--name
                  = item.name
                .ProductList__body--details
                  %ul
                    %li 
                      = item.price
                      円
                    %li
                      = icon('fa', 'star', class: "ProductList__body--details--likeIcon" )
                      1
                  %p (税込)

  %section.PickupContainer
    %h2.Title ピックアップブランド
    .ProductBox
      .ProductHead
        %a(href="#")
          %h3.ProductHead__title アーカイバ
      .ProductLists
        - @items.each do |item|
          .ProductList
            = link_to item_path(item.id), data: {"turbolinks" => false}  do
              %figure.ProductList__img
                = image_tag item.item_images[0].url.url
                - if item.purchases.present?
                  .ProductList__img__photo__sold
                    .ProductList__img__photo__sold__inner
                      SOLD
                - else
              .ProductList__body
                %h3.ProductList__body--name 
                  = item.name
                .ProductList__body--details
                  %ul
                    %li 
                      = item.price
                      円
                    %li
                      = icon('fa', 'star', class: "ProductList__body--details--likeIcon" )
                      1
                  %p (税込)
.Aside
  = render "layouts/aside"
.Footer
  = render "layouts/footer"
.Purchasebtn
  = render "layouts/purchasebtn"

app/views/items/new.html.haml
.sell__header
  .sell__header__logo
    = link_to "/" do
      = image_tag("material/logo/logo.png",class: 'sell__header__logo')
=form_with model: [@item], local: true do |f|
  .sell-container
    .sell-container__white
      .sell-box
        .sell-title
          .sell-title__group
            %label.sell__text
              出品画像
            %span.sell__require
              必須
          %p.sell-title__update
            最大5枚までアップロードできます
          #sell-image
            #previews
            .sell-image__box#image-box__container
              %i.fas.fa-camera
              %p.sell-image__box__text
                クリックしてファイルをアップロード
              =f.fields_for :item_images do |i|
                .sell-image__box__input{"data-index": "#{i.index}"}
                  = i.file_field :item_image, type: 'file', name: "item[item_images_attributes][#{i.index}][url]",class:"js-file", id:"item_item_images_attributes_0_url"
                  %label{for: "img-file"}
      .sell-box
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              商品名
            %span.sell__require
              必須
          =f.text_field :name, class: 'sell-title__text', placeholder: "40字まで"
        .sell-title
          .sell-title__group
            %label.sell__text
              商品の説明
            %span.sell__require
              必須  
          =f.text_area :explanation, class: 'sell-title__textbox', placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。\n          ",rows: "7"
          %p.word_count
            1000文字以内
      .sell-box
        .sell-box__header
          .sell__head
            %p 商品の詳細
        .sell-title__bottoms
          .sell-title__categoryWrapper
            %label.sell-title__categoryWrapper__text
              カテゴリー
            %span.sell-title__categoryWrapper__require
              必須
          .listing-select-wrapper
          =f.collection_select :category_id, @category_parent_array, :id, :name,{ include_blank: "選択してください"}, class:"listing-select-wrapper--select"
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              サイズ
            %span.sell__require
              必須
          =f.collection_select :size_id, Size.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              ブランド
            %span.sell__require__gray
              任意
          -# %input{autocomplete: "off",name: "name", placeholder: "例） Apple", type: "text", value: "",class: "sell-title__text"}/
          =f.text_field :brand, class: 'sell-title__text', placeholder: "例） Apple"

        .sell-title
          .sell-title__group
            %label.sell__text
              商品の状態
            %span.sell__require
              必須
          =f.collection_select :state_id, State.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
      .sell-box
        .sell-box__header
          .sell__head
            %p 配送について
          = link_to "#" do
            %i.far.fa-question-circle
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              配送料の負担
            %span.sell__require
              必須
          =f.collection_select :shipping_charge_id, ShippingCharge.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
        .sell-title__bottom
          .sell-title__group
            %label.sell__text
              発送元の地域
            %span.sell__require
              必須
          =f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
        .sell-title
          .sell-title__group
            %label.sell__text
              発送までの日数
            %span.sell__require
              必須
          =f.collection_select :shipping_date_id, ShippingDate.all, :id, :name, {include_blank: "選択してください"}, {class: "sell-title__select"}
      .sell-box
        .sell-box__header
          .sell__head
            %p 価格（¥300〜9,999,999）
          = link_to "#" do
            %i.far.fa-question-circle
        .sell-title
          .sell-title__price
            %label.sell__text
              販売価格
            %span.sell__require
              必須
            %span.sell__price
              ¥
            =f.number_field :price, min:300,max:999999999,placeholder: 0, id:"sell__box"
          .price__fee
            .price__commission
              %span.price__commission__left
                販売手数料（10%)
              %span.price__commission__right —
          .price__profit
            .price__commission
              .price__commission__left
                販売利益
              .profit__commission__right —
          .btn-group
            .submit-btn
              =f.submit "出品する",class: "submit-btn__mint",id: "mint_id",tabindex: 0
              =f.submit "下書きに保存",class: "submit-btn__gray",tabindex: 0
              -# %button.submit-btn__mint{tabindex: "0", type: "submit"} 出品する
              -# %button.submit-btn__gray{tabindex: "0", type: "submit"} 下書きに保存
            %li.link__back
              = link_to "もどる", "/"
          .sell-ban
            %p.sell-ban__text
              禁止されている
              %a.ban__text{href: "#"}> 行為
              および
              %a.ban__text{href: "#"}> 出品物
              を必ずご確認ください。
              %a.ban__text{href: "#"}> 偽ブランド品
              や
              %a.ban__text{href: "#"}> 盗品物
              などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
              %a.ban__text{href: "#"}> 加盟店規約
              に同意したことになります。
  .sell__footer
    %ul.sell__footer__link
      %li.link__text
        = link_to "プライバシーポリシー", "#"
      %li.link__text
        = link_to "フリマ利用規約", "#"
      %li.link__text
        = link_to "特定商取引に関する表記", "#"
    .sell__footer__logo
      = link_to "/" do
        = image_tag("material/logo/logo-white.png",class: 'sell__footer__logo')
    .sell__footer__inc
      © Furima, Inc.

app/views/items/show.html.haml
.Header
  = render "layouts/header"
%nav.BreadCrumbs
  %ul
    %li
      = link_to "FURIMA", "#"
    %li
      %i.fa.fa-angle-right
    %li
      =link_to "ベビー・キッズ", "#"
    %li
      %i.fa.fa-angle-right
    %li
      =link_to "ベビー服(男の子用)  ~95cm"
    %li
      %i.fa.fa-angle-right
    %li
      = link_to "アウター","#"
    %li
      %i.fa.fa-angle-right
    %li
      %p Tシャツ
.ProductMain
  .ShowMain
    .Content
      .ItemBox
        .ItemBox__name
          = @item.name
        .ItemBox__images
          %ul
            %li
              .ItemBox__images__first
              = image_tag @item.item_images.first.url.url, alt: "image1"
              - if @item.purchases.present?
                .items-box_photo__sold
                  .items-box_photo__sold__inner
                    SOLD
              - else
              %ul
                - @item_images.each do |item_image|
                  %li
                    = image_tag item_image.url.url, size: "75×75", alt: "image"
        .ItemBox__price
          %span 
            ¥
            = @item.price.to_s(:delimited) 
            -# to_s(:delimited)が価格にカンマをいれる記述
          .ItemBox__price__detail
            %span (税込)
            %span
              = @item.shipping_charge.name
        .ItemBox__description
          = @item.explanation
        .ItemBox__table
          %table
            %tbody
              %tr
                %th 出品者
                %td 
                  = @item.user.nickname
              %tr
                %th カテゴリー
                - if [46, 74, 134, 142, 147, 150, 158].include?(@category_id)
                  %td
                    = link_to "#{@category_child.name}","#"
                    %br= link_to "#{@category_grandchild.name}","#" 
                -else
                  %td
                    = link_to "#{@category_parent.name}","#"
                    %br= link_to "#{@category_child.name}","#"
                    = link_to "#{@category_grandchild.name}","#"
              %tr
                %th ブランド
                %td
                  = @item.brand
              %tr
                %th 商品のサイズ
                %td
                  = @item.size.name
              %tr
                %th 商品の状態
                %td 
                  = @item.state.name
              %tr
                %th 配送料の負担
                %td 
                  = @item.shipping_charge.name
              %tr
                %th 発送元の地域
                %td
                  = link_to "#{@item.prefecture.name}", "#"
              %tr
                %th 発送日の目安
                %td
                  = @item.shipping_date.name
        .ItemBox__option
          %ul
            %li.ItemBox__option__likeBtn
              = link_to "#" do
                %i.fa.fa-star
                お気に入り 0
          %ul.optional
            %li.ItemBox__option__optionalBtn
              = link_to "#" do
                %i.fa.fa-flag
                不適切な商品の通報

        - if user_signed_in?  && current_user.id != @item.user_id
          - if @item.purchases.present?
            .Box
              .Text
                SOLD OUT
          -else
            .Box
              = link_to "#{@item.id}/purchases/buy", method: :get do
                .PurchaseButton
                  = icon('fa', 'shopping-cart')
                  この商品を購入する
        - if user_signed_in?  && current_user.id == @item.user_id
          .Box
            = link_to edit_item_path(@item.id), method: :get do
              .EditButton
                = icon('fa', 'edit')
                この商品を編集する
          .Box
            = link_to item_path, method: :delete do
              .DeleteButton
                = icon('fa', 'trash')
                この商品を削除する
      .CommentBox
        %textarea.CommentBox__body
        .CommentBox__msg
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %button.CommentBox__btn(name="button" type="submit")
          %i.fa.fa-comment
          コメントする
      %ul.MoreLink
        %li.MoreLink__left
          = link_to "#" do
            %i.fa.fa-angle-left
            %span 前の商品
        %li.MoreLink__right
          = link_to "#" do
            %span 後ろの商品
            %i.fa.fa-angle-right
      .MoreItems
        = link_to "#{@item.category.name}をもっと見る","#"
        .MoreItems__lists
          .MoreItems__lists__list
            = link_to "/products/3" do
              %figure.MoreItems__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png"
              .MoreItems__lists__list__productBody
                %h3.MoreItems__lists__list__productBody__name
                  product3
                .MoreItems__lists__list__productBody__details
                  %ul
                    %li 30000円
                    %li
                      %i.fa.fa-star.likeIcon
                      0
                  %p (税込)
      
.Aside
  = render "layouts/aside"
.Footer
  = render "layouts/footer"
.Purchasebtn
  = render "layouts/purchasebtn"