config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
    member do
      get 'get_category_children', defaults: { format: 'json'}
      get 'get_category_grandchildren', defaults: { format: 'json'}
    end
  end
  resources "items", only: [:show] do
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  resources :users, only: :show
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :customer_id,:card_id, presence: true
  Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp" 
  Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

  def new
    @card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if @card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    if params["payjp_token"].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to user_path(current_user.id)
      else
        redirect_to action: "create"
      end
    end
  end
  def show
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
      end
  end

  def destroy
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      if @card.destroy
        redirect_to action: "new"
        flash[:notice] = 'カード情報を削除しました'
      else
        redirect_to card_path(current_user.id), alert: "削除できませんでした。"
      end
    end
  end
end

app/views/cards/new.html.haml
.Header
  = render "layouts/header"
.UserMain
  .main
    .user
      = render "users/user_side"
    .Main
      .Title クレジットカード情報入力
      = form_tag(cards_path, method: :post, id: "charge-form", class: "FormBox", name: "inputForm") do
        .CardNumber
          .CardNumber__text
            .CardNumber__text__comment
              カード番号
            .CardNumber__text__icon
              必須
          = text_field_tag 'payment_card_no', "", class: 'CardNumber__inputBox', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
          .CardNumber__image
            = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/visa-91c71914c6ae23d33f896e60bb1e3859.svg", class: "CardNumber__image__icon")
            = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/mastercard-8b5b68c12b7a2fc8619c71f49ef9209b.svg", class: "CardNumber__image__icon")
            = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/saison-550107415f39b81fa19e87c96486ba20.svg", class: "CardNumber__image__icon")
        .CardDeadline
          .CardDeadline__text
            .CardDeadline__text__comment
              有効期限
            .CardDeadline__text__icon
              必須
          .CardDeadline__inputBox
            .CardDeadline__inputBox__selectArea
              %select#payment_card_month.card-default{class: "CardDeadline__inputBox__selectArea__month", name: "payment_card_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月
              %select#payment_card_year.card-default{class: "CardDeadline__inputBox__selectArea__year", name: "payment_card_year", type: "text"}
                %option{value: ""} --
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
                %option{value: "2030"}30
              %span 年
        .CardSecurityCode
          .CardSecurityCode__text
            .CardSecurityCode__text__comment
              セキュリティコード
            .CardSecurityCode__text__icon
              必須
          = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'CardSecurityCode__inputBox', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
        = submit_tag "登録する", class: "RegistrationBtn", id: "payment_card_submit-button"
.Aside
  = render "layouts/aside"
.Footer
  = render "layouts/footer"
.Purchasebtn
  = render "layouts/purchasebtn"

app/views/cards/show.html.haml
.Header
  = render "layouts/header"
.UserMain
  .main
    .user
      = render "users/user_side"
    .Content
      .Title 支払い方法
      .Contents
        .Text  クレジットカード
        .Card
          .Card__info
            .Card__info__number  
              = "**** **** **** " + @customer_card.last4
            .Card__info__deadline
              = @exp_month + " / " + @exp_year
          .Card__delete
            = link_to new_card_path, method: :delete, class: "destroy__function__link__btn" do
              削除する
        .NewCard
          .NewCard__btn
            = link_to new_card_path, method: :delete, class: "NewCard__btn" do
              カードを再登録する
.Aside
  = render "layouts/aside"
.Footer
  = render "layouts/footer"
.Purchasebtn
  = render "layouts/purchasebtn"